### ISSUE TITLE
anchor "accommodation button to scroll down to section

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/vkirirom.com#13]
Eventually, clicking on this will open a search page showing all accommodations, but we have not built the search page template yet. 

![image](https://user-images.githubusercontent.com/5694308/57905521-0b876080-78a1-11e9-9cb3-faeb33293bdf.png)

**Comment by atharva3010** [comment]
I have made a function for the same and have included it in my PR. However, I am stuck with a minor bug, it's a work in progress. Please take a look at #14

**Comment by atharva3010** [comment]
I have fixed this issue, please review #17
