### ISSUE TITLE
change favcon to vkirirom logo

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/vkirirom.com#26]

**Comment by atharva3010** [comment]
Please provide the link to a favicon file for the same @paulchrisluke

**Comment by paulchrisluke** [comment]
![59732987_757726477956932_7350989801601892352_n](https://user-images.githubusercontent.com/5694308/58999640-e0a18400-8830-11e9-84ec-fb39193fcfac.png)

**Comment by atharva3010** [comment]
Done
