### ISSUE TITLE
add sub pages

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/vkirirom.com#4]
currently we have a /listing/ page template. We need the following pages created matching that template but with the page content found here:

https://drive.google.com/drive/u/0/folders/1thH8Fj4TrztfHnb71W26puszz83FRhRj
https://docs.google.com/document/d/10I3C5I7tanJSthxr2ydl6_1xay8aTO8N60Coam3WtOU/edit?usp=sharing

The goal is to style close to https://www.airbnb.com/rooms/432044?search_id=5a680883-1031-a175-a54a-e0b0dace7a5f&federated_search_id=7b0f216e-43c1-47dd-80b2-f4510697835f

Pages can be static for now since time is the most important issue with this site. Eventually, we will want to dynamically call page content from the meredith API. 

form handling on that page is handled in a related issue.

**Comment by paulchrisluke** [comment]
going with dynamic pages.

**Comment by paulchrisluke** [comment]
data loaded into the postgres database, you can use test api: https://stagingapi.whynot.earth/api/v0/pages/slug/vkirirom/testslug/

**Comment by atharva3010** [comment]
This has been resolved.
